# Generated by Django 4.1.2 on 2022-10-07 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_choise_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='questiom_text',
            new_name='question_text',
        ),
    ]
