name: Tests

on: pull_request

env:
  CI: true

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install
        run: pip3 install requirements.txt
      - name: Unit tests
        run: python manage.py test
      - name: Format tests
        run: djlint . --check